config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#top'
  get '/about' => 'books#about'
  resources :books
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :Opinion, length: { in: 1..200 }
	validates :Title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


validates :name, length: { in: 2..20 },presence: true
validates :introduction, length: { maximum: 50 }

  attachment :image

  has_many :books

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
	def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  	end

 	def after_sign_in_path_for(resource)
 		user_path(current_user.id)
	end

	def after_sign_up_path_for(resource)
		user_path.id(current_user.id)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only:[:index, :new, :edit, :create, :show,]
  # before_action :authenticate_current_user!, only:[:edit]
  def top
  end

  def about
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    if Book.find_by(id: params[:id])

      @book_show = Book.find(params[:id])
      @user = User.find(current_user.id)
      @book = Book.new

    else redirect_to books_path
    end
  end

  def new
  end

  def edit
    @book = Book.find(params[:id])
        if @book.user_id != current_user.id
          redirect_to book_path
        end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(book.id)
    else
      render :edit
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
      if @book.save
        redirect_to books_path
      else
        @books = Book.all
        render :index
      end

  end
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to user_path(current_user.id)
    
  end

  private
  def book_params
        params.require(:book).permit(:Title, :Opinion, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    # before_action :current_user!, only:[:edit]
  def show

    if User.find_by(id: params[:id])

  	@user = User.find(params[:id])
  	@book = Book.new
    @books_show = @user.books

  else redirect_to users_path
    end
  end

  def index
  	@users = User.all
  	@book = Book.new
    @user = User.find(current_user.id)
  end

  def edit
      @user = User.find(params[:id])
        if @user != current_user
          redirect_to users_path
        end

    end


    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
    end


 private
  def user_params
        params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_side.html.erb


		<h2>User info</h2>
			<div class="icon_div">

<%= attachment_image_tag(user, :image, :fill, 100, 100, format:'jpeg', fallback: "noimage.png",size: '100x100', class: "icon") %>

			</div>
		<table class="table">
			<thead>
				<tr>
					<th>name</th>
					<th><%= user.name %></th>
				</tr>
				<tr>
					<th>introduction</th>
					<th><%= user.introduction %></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<% if user.id == current_user.id %>
					<td><%= link_to "プロフィール編集", edit_user_path(current_user), class: "btn btn-success" %></td>
					<% end %>
				</tr>
				
			</tbody>
		</table>
		





<h2>New book</h2>



<%= form_for(book) do |f| %>

<h4>Title</h4>
<%= f.text_field :Title, class: "form-group form-control" %>

<h4>Opinion</h4>
<%= f.text_area :Opinion, class: "form-group form-control" %>
<br>
<%= f.submit "新規投稿", class: "btn btn-default" %>

<% end %>



app/views/books/about.html.erb
<h1>Welcome to Bookers!</h1>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>件のエラーがあります。</h2>
 
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>

<h4>Title</h4>
<%= f.text_field :Title, class: "form-group form-control" %>

<h4>Opinion</h4>
<%= f.text_area :Opinion, class: "form-group form-control" %>

<%= f.submit "Update Book", class: "btn btn-default" %>

<% end %>
<%= link_to "Show" , book_path(@book.id)  %>
<%= link_to "Books", books_path %>

app/views/books/index.html.erb

<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<%= render 'books/side', book: @book, user: current_user %>
		</div>
		<div class="col-lg-8">
			<% if @book.errors.any? %>
			  <div id="error_explanation">
			    <h2><%= @book.errors.count %>件のエラーがあります。</h2>
			    <ul>
			    <% @book.errors.full_messages.each do |msg| %>
			      <li><%= msg %></li>
			    <% end %>
			    </ul>
			  </div>
			<% end %>
			<h2>Books</h2>
			<table class="table table-hover">
				<thead>
					<tr>
						<th>icon</th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |data| %>
						<tr>
							<td><%= attachment_image_tag(data.user, :image, :fill, 30, 30, format:'jpeg', fallback: "noimage.png",size: '30x30', class: "icon") %>
</td>
							<td><%= link_to data.Title, book_path(data.id) %></td>
							<td><%= data.Opinion %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
	<div class="row">

		<div class="col-lg-4">
			<%= render 'books/side', book: @book, user: @book_show.user %>
			
		</div>

		<div class="col-lg-8">
		<h2>Book</h2>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Title</th>
						<th>Opinion</th>
					</tr>

				</thead>
				<tbody>
					<tr>
						<td><%= @book_show.Title %></td>
						<td><%= @book_show.Opinion %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/top.html.erb
<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>

<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>bookers,<br>
you can share and exchange your opinions , inpressions , and emotions<br>
about varioinus books!</p>

<%= link_to new_user_session_path do %>
    <div class="btn btn-info">Log_in</div>
<% end %>
<%= link_to new_user_registration_path do %>
    <div class="btn btn-warning">Sign_up</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
      <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <p class="navbar-brand">Bookers</p>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li class="">
        <%= link_to ' Home',user_path(current_user.id), class: "glyphicon glyphicon-home" %>
      </li>
      <li class="">
        <%= link_to ' Users',users_path, class: "glyphicon glyphicon-user" %>
      </li>
      <li class="">
        <%= link_to ' Books',books_path, class: "glyphicon glyphicon-book" %>
      </li>
      <li class="">
        <%= link_to ' Log_out',destroy_user_session_path, class: "glyphicon glyphicon-log-out", method: :delete %>
      </li>
      <% else %>
      <li class="">
        <%= link_to" Home",root_path, class: "glyphicon glyphicon-home" %>
      </li>
      <li class="">
        <%= link_to" About",about_path, class: "glyphicon glyphicon-star" %>
      </li>
      <li class="">
        <%= link_to" sign_up",new_user_registration_path, class: "glyphicon glyphicon-user" %>
      </li>
      <li class="">
        <%= link_to" login",new_user_session_path, class: "glyphicon glyphicon-log-in" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>





    <%= yield %>


      <footer id="footer" class="">CopyRight Infratop.inc</footer>

  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<h1>User info</h1>
<%= form_for(@user) do |f| %>
<h4>name</h4>
<%= f.text_field :name , class: "form-group form-control"%>

<h4>image</h4>
<%= f.attachment_field :image, class: "form-group form-control"  %>

<h4>introduction</h4>
<%= f.text_area :introduction, class: "form-group form-control" %>

<%= f.submit "Update User", class: "btn btn-default" %>

<% end %>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<%= render 'books/side', book: @book, user: @user %>
		</div>
		<div class="col-lg-8">
			<h2>Users</h2>
			<table class="table table-hover">
				<thead>
					<tr>
						<th></th>
						<th>name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |data| %>
						<tr>
							<td></td>
							<td><%= data.name %></td>
							<td><%= link_to "show",user_path(data.id) %></td>

						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
</body>
</html>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<%= render 'books/side', book: @book, user: @user %>
		</div>
		<div class="col-lg-8">
			<h2>Books</h2>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books_show.each do |data| %>
						<tr>
							<td><%= data.Title %></td>
							<td><%= data.Opinion %></td>
							<% if data.user == current_user %>
								<td><%= link_to "編集", edit_book_path(data), class: "btn btn-primary" %></td>
								<td><%= link_to "削除", book_path(data), method: :delete,data: { confirm: '削除しますか？' }, class: "btn btn-danger" %></td>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
</body>
</html>